package util;

import java.sql.*;

public final class Connect {

	private final String USERNAME = "root"; // Update with your MySQL username
	private final String PASSWORD = ""; // Update with your MySQL password
	private final String DATABASE = "gogoquery"; // Update with your database name
	private final String HOST = "localhost:3306"; // Update with your MySQL host
	private final String CONNECTION_STRING = String.format("jdbc:mysql://%s/%s", HOST, DATABASE);

	private Connection con;
	private Statement st;
	private static volatile Connect instance; // Use volatile for visibility across threads

	// Private constructor to prevent instantiation
	private Connect() {
		try {
			// Load the MySQL driver
			Class.forName("com.mysql.cj.jdbc.Driver");
			// Establish connection
			con = DriverManager.getConnection(CONNECTION_STRING, USERNAME, PASSWORD);
			st = con.createStatement();
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("Failed to connect to the database, the system is terminated!");
			System.exit(0); // Exit if connection fails
		}
	}

	// Singleton with double-checked locking for thread safety
	public static Connect getInstance() {
		if (instance == null) { // First check (without locking)
			synchronized (Connect.class) { // Lock on the class object
				if (instance == null) { // Second check (with locking)
					instance = new Connect();
				}
			}
		}
		return instance;
	}

	public ResultSet executeQuery(String query) throws SQLException {
		return st.executeQuery(query);
	}

	public void executeUpdate(String query) throws SQLException {
		st.executeUpdate(query);
	}

	public PreparedStatement prepareStatement(String query) throws SQLException {
		return con.prepareStatement(query);
	}

	public PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
		return con.prepareStatement(query, autoGeneratedKeys);
	}
}
